version: '3.8'
services:
  db:
    image: postgis/postgis:17-3.5
    restart: always
    env_file:
      - ../environment/local.env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ../initalization_scripts/:/docker-entrypoint-initdb.d/
volumes:
  db:
    driver: local