services:

  minio:
    image: minio/minio:latest
    container_name: prod-minio
    env_file:
      - ../environment/local.env
    ports:
      - "9000:9000"    
      - "9001:9001"
    volumes:
      - minio_prod_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_prod_data:
    driver: local